/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as OportunidadesRouteImport } from './routes/oportunidades'
import { Route as NpsRouteImport } from './routes/nps'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FormulariosRouteImport } from './routes/formularios'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as FestasRouteImport } from './routes/festas'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesIndexRouteImport } from './routes/configuracoes.index'
import { Route as FSlugRouteImport } from './routes/f.$slug'
import { Route as ConfiguracoesUnidadesRouteImport } from './routes/configuracoes.unidades'
import { Route as ConfiguracoesImportacaoHistoricaRouteImport } from './routes/configuracoes.importacao-historica'
import { Route as ConfiguracoesEquipeRouteImport } from './routes/configuracoes.equipe'
import { Route as AvaliarSlugRouteImport } from './routes/avaliar.$slug'
import { Route as ApiPublicMarketingEventRouteImport } from './routes/api/public/marketing-event'
import { Route as ApiPublicGa4OauthCallbackRouteImport } from './routes/api/public/ga4-oauth.callback'

const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesRoute = OportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const NpsRoute = NpsRouteImport.update({
  id: '/nps',
  path: '/nps',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulariosRoute = FormulariosRouteImport.update({
  id: '/formularios',
  path: '/formularios',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const FestasRoute = FestasRouteImport.update({
  id: '/festas',
  path: '/festas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesIndexRoute = ConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesUnidadesRoute = ConfiguracoesUnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesImportacaoHistoricaRoute =
  ConfiguracoesImportacaoHistoricaRouteImport.update({
    id: '/importacao-historica',
    path: '/importacao-historica',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const ConfiguracoesEquipeRoute = ConfiguracoesEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const AvaliarSlugRoute = AvaliarSlugRouteImport.update({
  id: '/avaliar/$slug',
  path: '/avaliar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarketingEventRoute = ApiPublicMarketingEventRouteImport.update({
  id: '/api/public/marketing-event',
  path: '/api/public/marketing-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGa4OauthCallbackRoute =
  ApiPublicGa4OauthCallbackRouteImport.update({
    id: '/api/public/ga4-oauth/callback',
    path: '/api/public/ga4-oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/festas': typeof FestasRoute
  '/financeiro': typeof FinanceiroRoute
  '/formularios': typeof FormulariosRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/nps': typeof NpsRoute
  '/oportunidades': typeof OportunidadesRoute
  '/webhooks': typeof WebhooksRoute
  '/avaliar/$slug': typeof AvaliarSlugRoute
  '/configuracoes/equipe': typeof ConfiguracoesEquipeRoute
  '/configuracoes/importacao-historica': typeof ConfiguracoesImportacaoHistoricaRoute
  '/configuracoes/unidades': typeof ConfiguracoesUnidadesRoute
  '/f/$slug': typeof FSlugRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/api/public/marketing-event': typeof ApiPublicMarketingEventRoute
  '/api/public/ga4-oauth/callback': typeof ApiPublicGa4OauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/festas': typeof FestasRoute
  '/financeiro': typeof FinanceiroRoute
  '/formularios': typeof FormulariosRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/nps': typeof NpsRoute
  '/oportunidades': typeof OportunidadesRoute
  '/webhooks': typeof WebhooksRoute
  '/avaliar/$slug': typeof AvaliarSlugRoute
  '/configuracoes/equipe': typeof ConfiguracoesEquipeRoute
  '/configuracoes/importacao-historica': typeof ConfiguracoesImportacaoHistoricaRoute
  '/configuracoes/unidades': typeof ConfiguracoesUnidadesRoute
  '/f/$slug': typeof FSlugRoute
  '/configuracoes': typeof ConfiguracoesIndexRoute
  '/api/public/marketing-event': typeof ApiPublicMarketingEventRoute
  '/api/public/ga4-oauth/callback': typeof ApiPublicGa4OauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/contratos': typeof ContratosRoute
  '/dashboard': typeof DashboardRoute
  '/festas': typeof FestasRoute
  '/financeiro': typeof FinanceiroRoute
  '/formularios': typeof FormulariosRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/nps': typeof NpsRoute
  '/oportunidades': typeof OportunidadesRoute
  '/webhooks': typeof WebhooksRoute
  '/avaliar/$slug': typeof AvaliarSlugRoute
  '/configuracoes/equipe': typeof ConfiguracoesEquipeRoute
  '/configuracoes/importacao-historica': typeof ConfiguracoesImportacaoHistoricaRoute
  '/configuracoes/unidades': typeof ConfiguracoesUnidadesRoute
  '/f/$slug': typeof FSlugRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/api/public/marketing-event': typeof ApiPublicMarketingEventRoute
  '/api/public/ga4-oauth/callback': typeof ApiPublicGa4OauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/festas'
    | '/financeiro'
    | '/formularios'
    | '/login'
    | '/marketing'
    | '/nps'
    | '/oportunidades'
    | '/webhooks'
    | '/avaliar/$slug'
    | '/configuracoes/equipe'
    | '/configuracoes/importacao-historica'
    | '/configuracoes/unidades'
    | '/f/$slug'
    | '/configuracoes/'
    | '/api/public/marketing-event'
    | '/api/public/ga4-oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contratos'
    | '/dashboard'
    | '/festas'
    | '/financeiro'
    | '/formularios'
    | '/login'
    | '/marketing'
    | '/nps'
    | '/oportunidades'
    | '/webhooks'
    | '/avaliar/$slug'
    | '/configuracoes/equipe'
    | '/configuracoes/importacao-historica'
    | '/configuracoes/unidades'
    | '/f/$slug'
    | '/configuracoes'
    | '/api/public/marketing-event'
    | '/api/public/ga4-oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/festas'
    | '/financeiro'
    | '/formularios'
    | '/login'
    | '/marketing'
    | '/nps'
    | '/oportunidades'
    | '/webhooks'
    | '/avaliar/$slug'
    | '/configuracoes/equipe'
    | '/configuracoes/importacao-historica'
    | '/configuracoes/unidades'
    | '/f/$slug'
    | '/configuracoes/'
    | '/api/public/marketing-event'
    | '/api/public/ga4-oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  ContratosRoute: typeof ContratosRoute
  DashboardRoute: typeof DashboardRoute
  FestasRoute: typeof FestasRoute
  FinanceiroRoute: typeof FinanceiroRoute
  FormulariosRoute: typeof FormulariosRoute
  LoginRoute: typeof LoginRoute
  MarketingRoute: typeof MarketingRoute
  NpsRoute: typeof NpsRoute
  OportunidadesRoute: typeof OportunidadesRoute
  WebhooksRoute: typeof WebhooksRoute
  AvaliarSlugRoute: typeof AvaliarSlugRoute
  FSlugRoute: typeof FSlugRoute
  ApiPublicMarketingEventRoute: typeof ApiPublicMarketingEventRoute
  ApiPublicGa4OauthCallbackRoute: typeof ApiPublicGa4OauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades': {
      id: '/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof OportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nps': {
      id: '/nps'
      path: '/nps'
      fullPath: '/nps'
      preLoaderRoute: typeof NpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formularios': {
      id: '/formularios'
      path: '/formularios'
      fullPath: '/formularios'
      preLoaderRoute: typeof FormulariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festas': {
      id: '/festas'
      path: '/festas'
      fullPath: '/festas'
      preLoaderRoute: typeof FestasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/': {
      id: '/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof ConfiguracoesIndexRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/unidades': {
      id: '/configuracoes/unidades'
      path: '/unidades'
      fullPath: '/configuracoes/unidades'
      preLoaderRoute: typeof ConfiguracoesUnidadesRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/importacao-historica': {
      id: '/configuracoes/importacao-historica'
      path: '/importacao-historica'
      fullPath: '/configuracoes/importacao-historica'
      preLoaderRoute: typeof ConfiguracoesImportacaoHistoricaRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/equipe': {
      id: '/configuracoes/equipe'
      path: '/equipe'
      fullPath: '/configuracoes/equipe'
      preLoaderRoute: typeof ConfiguracoesEquipeRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/avaliar/$slug': {
      id: '/avaliar/$slug'
      path: '/avaliar/$slug'
      fullPath: '/avaliar/$slug'
      preLoaderRoute: typeof AvaliarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/marketing-event': {
      id: '/api/public/marketing-event'
      path: '/api/public/marketing-event'
      fullPath: '/api/public/marketing-event'
      preLoaderRoute: typeof ApiPublicMarketingEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ga4-oauth/callback': {
      id: '/api/public/ga4-oauth/callback'
      path: '/api/public/ga4-oauth/callback'
      fullPath: '/api/public/ga4-oauth/callback'
      preLoaderRoute: typeof ApiPublicGa4OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConfiguracoesRouteChildren {
  ConfiguracoesEquipeRoute: typeof ConfiguracoesEquipeRoute
  ConfiguracoesImportacaoHistoricaRoute: typeof ConfiguracoesImportacaoHistoricaRoute
  ConfiguracoesUnidadesRoute: typeof ConfiguracoesUnidadesRoute
  ConfiguracoesIndexRoute: typeof ConfiguracoesIndexRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesEquipeRoute: ConfiguracoesEquipeRoute,
  ConfiguracoesImportacaoHistoricaRoute: ConfiguracoesImportacaoHistoricaRoute,
  ConfiguracoesUnidadesRoute: ConfiguracoesUnidadesRoute,
  ConfiguracoesIndexRoute: ConfiguracoesIndexRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  ContratosRoute: ContratosRoute,
  DashboardRoute: DashboardRoute,
  FestasRoute: FestasRoute,
  FinanceiroRoute: FinanceiroRoute,
  FormulariosRoute: FormulariosRoute,
  LoginRoute: LoginRoute,
  MarketingRoute: MarketingRoute,
  NpsRoute: NpsRoute,
  OportunidadesRoute: OportunidadesRoute,
  WebhooksRoute: WebhooksRoute,
  AvaliarSlugRoute: AvaliarSlugRoute,
  FSlugRoute: FSlugRoute,
  ApiPublicMarketingEventRoute: ApiPublicMarketingEventRoute,
  ApiPublicGa4OauthCallbackRoute: ApiPublicGa4OauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
